### ISSUE TITLE
texworks crashes when pressing down arrow key in editor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#497] opened 2015-03-14 11:04 UTC
```
I don't know how to reproduce the problem; it is intermittent. It has only 
occurred since I upgraded Ubuntu from 10.10 to 11.04. 

The problem occurs occasionally when I press the down arrow key in the editor 
pane. I expect the cursor to move down to the next line of input. Instead 
texworks closes without saving my work.

I have had this same error in texworks 0.30 and 0.40. I am using Ubuntu 
GNU/Linux 11.04.

```

Original issue reported on code.google.com by `b.mckay....@gmail.com` on 15 May 2011 at 10:02

**Comment by stloeffler** [comment] 2016-03-17 11:47
Duplicate of #469

**Closed by stloeffler** 2016-03-17 11:47 UTC
Labels: auto-migrated, bug, Linux
