### ISSUE TITLE
Text Automatically Selected on Mouse Over Bug

### ISSUE THREAD

**Issue by blackhaz** [TeXworks/texworks#982] opened 2022-11-20 18:17 UTC
In the editor, the text is automatically selected when moving mouse over it - without pressing any buttons. 

**Steps to reproduce the problem:**

1. Open a TeX document. 
2. Move mouse over the text without pressing anything. 
3. Text is selected. 

**Expected behavior:**

Text should not be selected on mouse-over. 

**General information:**
_TeXworks version_: 0.6.2 r.7ecce17d, 29 Apr 2017 17:23:51
_TeXworks obtained from_: FreeBSD Packages Repository
_Operating system_: FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC

**Comment by stloeffler** [comment] 2022-12-26 16:41
Thanks for reporting. I haven't seen this issue before (but I don't have FreeBSD).
I noticed that the version is pretty old. Could you try compiling the latest stable or development versions (available here on GitHub) and try with one of those?

**Comment by chickazee4** [comment] 2023-01-06 21:27
Not the OP, but I did also have the same issue on 0.6.2, which is the latest *quarterly* version available for the FreeBSD 13.1. stloeffler had the right idea — the issue is not present on the pkg version of 0.6.7 or on the current main branch when compiled from source, so just upgrade to 0.6.7. To do this on 13.1 i386/amd64, you'll need to switch your default pkg repository configuration to latest instead of quarterly (if you don't want to mess with your pkg configuration, you can compile from source or simply wait for 0.6.7 to end up in quarterly).

**Comment by stloeffler** [comment] 2023-01-07 17:11
Thanks for confirming. Closing this here as it doesn't seem to affect the code (anymore).

**Closed by stloeffler** 2023-01-07 17:11 UTC
Labels: bug
