### ISSUE TITLE
Crash under certain circumstances for TeXworks

### ISSUE THREAD

**Issue by SSebastiano** [TeXworks/texworks#847] opened 2018-08-26 19:46 UTC
_Steps to reproduce the problem_:

1. I have followed the indications on this link: [crash TeXworks](https://github.com/TeXworks/texworks/issues/826)

_Expected output_: No mistakes.

_Actual output_: opens with errors with the windows messages https://tex.stackexchange.com/questions/447846/crash-under-certain-circumstances-for-texworks
problem occured  while laying out the loaded document in the editor. This is caused
by an issue in the underlying Qt framework and can cause TeXworks to crash under certain circumstances. The symptoms of this problem are hidden or overlapping lines. To work around this, please try one of the following: -) Turn syntax highlighting off and on -) Turn line numbers off and on -) Resize the windows We are sorry for the inconvenience"

_TeXworks version_: 0.6.2 (MikTeX 2.9.6800 64-bit of 29/04/2017).
_TeXworks obtained from_: MikTeX 2.9.6809 + console.
_Operating system_: W7 64-bit.

_Please provide any additional information below_: I have written all the information for my problems on this link: [TeX.SE.](https://tex.stackexchange.com/questions/447846/crash-under-certain-circumstances-for-texworks) and I have done the steps for a similar question at the link https://github.com/TeXworks/texworks/issues/826. I ask TeXworks maintainers to correct the error. As soon as I click on OK the file opens correctly. Thank you and I look forward to a response on my email.

**Comment by stloeffler** [comment] 2020-06-07 09:32
Closed because
 * the linked information on SE is no longer available
 * the error is reported against an outdated version of Tw
 * this seems to be a duplicate of #469 
 * the underlying problem is a Qt one - not a Tw one. It has has recently been fixed in the development version of Qt and will be implemented in Tw as soon as the respective Qt release versions become available

**Closed by stloeffler** 2020-06-07 09:32 UTC
