### ISSUE TITLE
Magnifier always sets itself to circular even if it was set to rectangular

### ISSUE THREAD

**Issue by bpump** [TeXworks/texworks#755] opened 2016-10-15 18:20 UTC
_Steps to reproduce the problem_:

1.  Edit -> Preferences -> Preview -> Magnifying glass -> Circular magnifier (uncheck)
2.  Close TeXworks
3.  Open TeXworks

_Expected output_: Rectangular magnifier

_Actual output_: Circular magnifier

_TeXworks version_: 0.6.1
_TeXworks obtained from_: www.tug.org/texworks/
_Operating system_: Windows 8.1

_Please provide any additional information below_:
I had an older version of TeXworks (cannot recall which one exactly) prior to installing the current 0.6.1 version a few days ago. I learned that "Preferences" from the previous version (which were not the defaults) were cached somewhere on the system because the new version imported them and had the same "Preferences" when I went to check them. What surprised me was that when I used magnifier it turned out to be a circular magnifier although the "Circular magnifier" box was unchecked in the "Preferences". So I decided to take a look at the "Preferences" again to make sure I was right and the box was unchecked (as expected) yet I had this circular magnifier on the screen. But not only was it circular (when it was supposed to be rectangular), it was constantly freezing barely following the movements of the mouse. What I did was go to the "Preferences" and check the box so that it would match the circular magnifier. Then I closed the "Preferences", moved the magnifier back and forth, went to the "Preferences" again to uncheck the box and finally it turned rectangular. But, unfortunately, that didn't solve the issue because when I closed the TeXworks and opened it again, the magnifier appeared circular again (this time being able to follow the mouse movements without freezing) in spite of the box still being unchecked.

**Comment by stloeffler** [comment] 2016-10-16 21:00
This looks like a duplicate of #745 which has already been fixed (though this fix was applied after the 0.6.1 release and is currently available only in the experimental builds).

**Closed by stloeffler** 2016-10-16 21:00 UTC
