### ISSUE TITLE
TeXworks editor lags on even moderately large files

### ISSUE THREAD

**Issue by gnilsiu** [TeXworks/texworks#963] opened 2022-03-02 22:56 UTC
Somebody has brought this issue up [earlier](https://github.com/TeXworks/texworks/issues/810) but it either hasn't been resolved or has resurfaced with a later version of TeXworks. I just have a moderately large LaTeX source --- 308 KB, 4300 lines, 56-page PDF when compiled --- but the TeXworks text editor is already noticeably sluggish. There's no problem for smaller-sized files. I thought maybe it's because my TeX file is on Google Drive but the problem persists after I moved it to my local hard drive. Also, like the user who raised this issue [earlier](https://github.com/TeXworks/texworks/issues/810), there was no problem with earlier versions of TeXworks; it's been two years since I worked on this file and back then there wasn't such an issue (it's so infuriatingly slow it wouldn't have gone unnoticed). Please help.

_TeXworks version_: 0.6.6
_TeXworks obtained from_:  GitHub
_Operating system_: macOS Monterey 12.2.1

**Comment by stloeffler** [comment] 2022-03-03 18:41
Interesting, I thought this was fixed. Anyway, could you answer the following questions:
1. Does this still happen with the latest 0.6.7 release?
2. Does this happen with disabled syntax highlighting and spell checking?
3. Does this happen after clearing the recent files (warning: this step can't be undone)
4. Could you provide a ("minimal") example file for which this problem occurs?

**Comment by lekheng** [comment] 2022-03-04 12:29
Thanks for responding! You have identified the problem. Once I disabled _both_ syntax highlighting and spell checking, the problem went away. But doing just one of the two didn't help, and neither did installing 0.6.7 nor did clearing recent files.

Right now I'm going to just do away with syntax highlighting and spell checking but it would be great if you could fix the issue in a future release. I assume the problem is caused by the program constantly updating the syntax highlighting and spell checking for the entire TeX document (4300 lines) instead of just the tiny part (84 lines on my Thunderbolt Display) displayed in the editor.

**Comment by gnilsiu** [comment] 2022-03-04 12:32
Thanks for responding! You have identified the problem. Once I disabled both syntax highlighting and spell checking, the problem went away. But doing just one of the two didn't help, and neither did installing 0.6.7 nor did clearing recent files.

Right now I'm going to just do away with syntax highlighting and spell checking but it would be great if you could fix the issue in a future release. I assume the problem is caused by the program constantly updating the syntax highlighting and spell checking for the entire TeX document (4300 lines) instead of just the tiny part (84 lines on my Thunderbolt Display) displayed in the editor.

**Comment by stloeffler** [comment] 2022-03-05 09:51
Unfortunately, "fixing this" may not be that easy. Syntax highlighting generally has to be done (at least once) for the entire document from top to bottom. The reason is that the syntax highlighting for line x could depend on the state of line x-1. Think of highlighting of environments (which is not implemented yet, but is definitely on the wishlist), e.g. everything between `\begin{comment}` and `\end{comment}` is grayed out, then for any given line the program has to know if on some preceding line (possibly hundreds of lines above) a relevant `\begin{...}` is found. The idea is that, instead of searching the entire document for `\begin{...}` on each line, a sort of state (e.g., "are we inside a comment") is maintained for each line. Hence, syntax highlighting has to be performed at least once for the entire document to properly set up this state information.

That said, the code tries to be smart about it. After the initial highlighting is done, only the part of the document that actually is affected by a change should be rehighlighted (e.g., the line you edit, plus, potentially, subsequent lines if the abovementioned state changed for some reason). Also, in order to not freeze the UI completely, highlighting is done in chunks, which should ideally last only a couple of milliseconds before breaking for a little while to let the UI process user interaction, updates, etc. On my system, this works fairly well, with a thousand lines of "lorem ipsum" being spell-checked in about a second or so (though this depends on the hardware, system load, etc. of course). During that time, the UI is a bit less responsive, but editing is still possible. After that, everything is "back to normal".

* What is the system load when opening your big file?
* Does the situation (responsiveness and/or system load) change over time, e.g. after a few seconds to a minute without editing?
* When you scroll to the end, when does highlighting appear there?
* Does it have any influence whether you are editing at the beginning or at the end of the document? Is TeXworks more/less responsive when editing on either side?

**Comment by gnilsiu** [comment] 2022-03-05 10:44
I downloaded a random moderately large TeX file from arXiv (e.g., [this 79-page paper](https://arxiv.org/abs/2203.01690), you can just click on "other formats" and select "source") and I get the same problem. So let's use this file as example.

- System load is low. In my Mac Activity Monitor, I see about 30% CPU load and less than 9GB out of 16GB physical memory used. TeXworks is essentially using 0% CPU and 60MB memory. The sluggish behavior is limited to the TeXworks editor. For example, it doesn't happen while I am writing these comments in Safari.

- The situation has not changed over the last 20 minutes or so.

- Yes the syntax highlighting appears all the way to the end.

- This is something I didn't observe before: At the beginning and at the end of the document, there's no lag at all when I type; it only happens in the middle of the document. This is probably why I didn't notice it when I was writing my long document --- because at that point I would mostly be adding text to the end. It is only after I finished the whole document and returned to edit the parts in the middle that I noticed the lag.

**Comment by stloeffler** [comment] 2022-03-05 14:12
Thanks for the example file. Unfortunately, I still can't reproduce the problem... everything runs smoothly for me, and my tests so far confirm that (after the initial run) only the edited line is reprocessed.
What's weird is that TeXworks does not seem to  be using resources. With significant lag, I would have expected at least 1 CPU core more or less fully occupied.
* Do you have anything running/activated that could be "triggered" by edits in the editor? I'm thinking of the "follow focus" feature, a script, a screen reader, etc.
* Does the problem persist if you close the PDF previewer?
* Does the problem occur only when inserting characters, or also when deleting characters, moving the cursor, scrolling, ...
* Does the problem occur also when copying/pasting text?

**Comment by gnilsiu** [comment] 2022-03-05 21:17
Thanks for taking this seriously. I really appreciate it.

- I don't think so. I get the lagging issue even when my Mac is booted up in Safe Mode and essentially the only program running is TeXworks (I did this a while ago; I'll check again later to make sure). Also, I do not use any of these features/programs you mentioned.
- Yes. In fact, with the file I downloaded from arXiv, I did not even compile. There's no PDF to be viewed.
- Only inserting and deleting (and only in the middle of the document; not when I scrolled right up to the top or right down to the bottom). Moving the cursor appears to be fine. Scrolling with my magic mouse is fine too.
- Copy/pasting is fine. No lag at all.

**Comment by stloeffler** [comment] 2022-03-06 07:55
Thanks for testing and answering my questions. Speaking of questions:
* Does it matter whether you edit at the beginning, middle, or end *of a line* (at the start, middle, and end of the document)?

**Comment by gnilsiu** [comment] 2022-03-06 09:19
I tried: Only the vertical coordinates make a difference, the horizontal coordinates don't matter. The arXiv document that I used as example has around 2600 lines. In the first 300 lines or so and last 300 lines or so, everything appears to be fine; but for the 2000 lines or so in the middle, the lag is very noticeable.

**Comment by stloeffler** [comment] 2022-03-08 06:16
I think I may finally have reproduced the issue. Unfortunately, it seems to be related to #469 and several (related) Qt bugs. If I am correct, there is no easy way of "fixing this" immediately. In the following, I will try to detail my hypothesis regarding how it came to this bug.

When you load (or edit) a document, the underlying Qt framework used for displaying, handling windows, etc. has to break the text into lines. Historically, it has done so incrementally (a few paragraphs at a time, "taking a break" every now and then to allow the program to do other things, such as process user input). Unfortunately, there was a very long standing bug ([QTBUG-20345](https://bugreports.qt.io/browse/QTBUG-20354)) in this process (dating back almost a decade now) resulting in the failure to lay out some lines if paragraph styling was changed (e.g. by a syntax highlighter or spell checker) before the layout process was complete. Naturally, this has a tendency to occur mostly for large documents where the layout process took some time (and some breaks). However navigating to one of those lines that were not laid out correctly resulted in the immediate crash of TeXworks (#469). As a phenomenological workaround, TeXworks checks if all lines are properly laid out and if not, "reloads" the document into Qt up to a couple of times.
[QTBUG-20345](https://bugreports.qt.io/browse/QTBUG-20354) was finally fixed for Qt 5.15.1 (in large part due to my initiative),  but unfortunately the fix introduced another bug ([QTBUG-89599](https://bugreports.qt.io/browse/QTBUG-89599)) - a performance regression when performing line layout in large documents. So while this fixed the "missing lines" issue and the associated crash, large documents are (very) slow to load (and edit) in Qt 5.15.1 and above (and loading may be slowed down additionally by to the "workaround" described above - though I have not benchmarked this in detail yet).
[QTBUG-89599](https://bugreports.qt.io/browse/QTBUG-89599) was also fixed (mostly by fixing the original [QTBUG-20345](https://bugreports.qt.io/browse/QTBUG-20354) in a better way), but unfortunately the fix seems to have landed only in Qt 6 and Qt 5.15.9. Qt 5.15.9 is only available for commercial uses (open source Qt 5.15 has been discontinued after 5.15.2), and TeXworks is not yet fully compatible with Qt 6, in part due to ever changing libraries trying themselves to adapt to the new major version of Qt.

So, what does this all mean. On macOS, you might get better performance (and potentially the disappearing lines that can crash the program) if you use the macOS 10.12 build (which uses the older Qt 5.12.12) or an older version of TeXworks (not really recommended, as it likely comes with the same issues in Qt, and potentially other issues in TeXworks that have since been fixed). On other OS, there is no such option (of current builds with older Qt) currently available. The real solution should be the migration to Qt 6, which I am currently working on (but these things take time). Also, if you are on Linux (in particular on any but the cutting edge versions), Qt 6 may not be available in the repositories, so I'll try to continue Qt 5 support in parallel to Qt 6 support for the foreseeable future.

**Comment by gnilsiu** [comment] 2022-03-08 20:48
Thanks very much for the efforts. I will just be patient and wait for the eventual migration to Qt6. In the mean time I'll just edit long documents without syntax highlighting and spellcheck. While waiting for your response I have been trying to build TeXworks from source to see if it might help. It is taking a long time because I use MacPorts instead of Homebrew (BTW, perhaps you could provide a MacPorts guide for building TeXworks in the future) so I guess I can stop now.

**Comment by stloeffler** [comment] 2022-03-09 06:02
The code should have (basic) support for Qt 6 now. I have updated the [homebrew build instructions](https://github.com/TeXworks/texworks/wiki/Building-on-macOS-(Homebrew)) to use Qt 6 (since homebrew no longer ships Qt 5) if you or someone else wants to give it a try. There is still quite a way to go to update all (automated) build scripts and test everything (also on other OSs), though.

Re. MacPorts, there used to be some instructions, but they were so outdated and untested that they were practically useless. I'm not really a Mac developer myself, but I'll see what I can do. However, it seems that the [Macports version of poppler](https://ports.macports.org/port/poppler/details/) currently only supports Qt 5 anyway, so this would not help for the particular problem at hand...

**Comment by gnilsiu** [comment] 2022-03-09 06:54
Poppler was in fact the thing that was stalling me; I couldn't install it properly with MacPorts. Since Homebrew doesn't coexist well with Macports, all recommendations on the web say to uninstall Macports first before switching to Homebrew. So to build TeXworks with Homebrew would be quite a major operation for me; while it is the least I can do to thank you for your very kind assistance this past week, I'm going to have to plan it carefully. I assume some other user had built the binaries for Mac at https://github.com/TeXworks/texworks/releases on your behalf? Could you ask him/her to do it again with Qt6? If not, I'll do it next weekend and let you know how it turns out.

**Comment by stloeffler** [comment] 2022-03-10 22:32
No need to (potentially) mess up your system, I'm working on a build (which is semi-working by now but still requires some polishing).
The binaries are built automatically on Github, which generally is very useful, but makes updating the build process a pain.

**Comment by stloeffler** [comment] 2022-03-11 08:43
A Qt 6 test build is available now at <https://nightly.link/TeXworks/texworks/workflows/cd/master/TeXworks-macOS>

**Comment by josephwright** [comment] 2022-03-11 08:46
Initial test (`siunitx` v2 `.dtx`, about 12k lines) looks good: stays responsive whilst the highlighting is happening.

**Comment by gnilsiu** [comment] 2022-03-11 08:50
The test build works perfectly! There's no more lag. Thank you very much!

**Comment by gnilsiu** [comment] 2022-03-26 20:22
I guess I was too quick to say that there's no more lag. After two weeks of working with the new version, I notice that although it's a big improvement over the previous version, there's still a noticeable lag when editing the middle of a large file. I suppose this can't be helped?

**Comment by stloeffler** [comment] 2022-04-16 19:06
For the moment, I'm afraid so, unless there are some additional bugfixes/performance improvements. Generally, I would recommend splitting very large tex files into subdocuments anyway, but that's beside the point.
Closing this for now as the original problem seems to be fixed.

**Closed by stloeffler** 2022-04-16 19:06 UTC
Labels: bug
