### ISSUE TITLE
TexWorks crashes. Segfault.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#656] opened 2015-03-14 11:05 UTC
```
What steps will reproduce the problem?
1. Open TexWorks
2. Edit a LaTeX file
3. Add a blank line, or delete it. Use direction arrows up or down. Eventually 
it will crash.

What is the expected output? What do you see instead?
I see what I expect to see. No problem there.

What version of the product are you using? On what operating system?
I installed TexWorks using apt-get install. According to dpkg, the version of 
the installed package is : 0.5~svn1351-1 and the architecture of the installed 
package is : amd64.

Please provide any additional information below.

Installed package :
$ sudo dpkg -l texworks
$ ii  texworks                                              0.5~svn1351-1       
            amd64                           Environment for authoring TeX 
(LaTeX, ConTeXt, etc) documents

I ran TexWorks inside gdb :
$ gdb /usr/bin/texworks
GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/texworks...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/texworks 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe466a700 (LWP 26950)]
[New Thread 0x7fffe3e69700 (LWP 26951)]
[New Thread 0x7fffe3668700 (LWP 26952)]
[New Thread 0x7fffe2e67700 (LWP 26953)]
[New Thread 0x7fffd0fec700 (LWP 26954)]
[Thread 0x7fffe2e67700 (LWP 26953) exited]
[New Thread 0x7fffe2e67700 (LWP 26955)]
[New Thread 0x7fffc7fff700 (LWP 26956)]
[Thread 0x7fffe3668700 (LWP 26952) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff625c8bc in QTextLine::textStart() const () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) bt
#0  0x00007ffff625c8bc in QTextLine::textStart() const () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#1  0x00007ffff62992bd in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#2  0x00007ffff629b994 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#3  0x00007ffff629cc7b in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#4  0x00007ffff62a4924 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#5  0x00007ffff624c2ff in QTextControl::drawContents(QPainter*, QRectF const&, 
QWidget*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#6  0x00007ffff646005a in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x00007ffff646010c in QTextEdit::paintEvent(QPaintEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#8  0x00007ffff60572f0 in QWidget::event(QEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007ffff63f8fce in QFrame::event(QEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007ffff5ad6646 in 
QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () 
from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#11 0x00007ffff6007e0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) 
() from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#12 0x00007ffff600e4a0 in QApplication::notify(QObject*, QEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff5ad64dd in QCoreApplication::notifyInternal(QObject*, QEvent*) 
() from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x00007ffff6051a11 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion 
const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007ffff621485a in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#16 0x00007ffff6046ea0 in QWidgetPrivate::syncBackingStore() () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#17 0x00007ffff6056e6a in QWidget::event(QEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#18 0x00007ffff64119b3 in QMainWindow::event(QEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00000000004aaf32 in TeXDocument::event(QEvent*) ()
#20 0x00007ffff6007e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) 
() from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x00007ffff600e4a0 in QApplication::notify(QObject*, QEvent*) () from 
/usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x00007ffff5ad64dd in QCoreApplication::notifyInternal(QObject*, QEvent*) 
() from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#23 0x00007ffff5ad9b3d in QCoreApplicationPrivate::sendPostedEvents(QObject*, 
int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#24 0x00007ffff5b03f83 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#25 0x00007ffff3da0e04 in g_main_context_dispatch () from 
/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff3da1048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff3da10ec in g_main_context_iteration () from 
/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff5b037a1 in 
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () 
from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x00007ffff60a9bb6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007ffff5ad50af in 
QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from 
/usr/lib/x86_64-linux-gnu/libQtCore.so.4
#31 0x00007ffff5ad53a5 in 
QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from 
/usr/lib/x86_64-linux-gnu/libQtCore.so.4
#32 0x00007ffff5adab79 in QCoreApplication::exec() () from 
/usr/lib/x86_64-linux-gnu/libQtCore.so.4
#33 0x0000000000467819 in main ()
(gdb) info thread
  Id   Target Id         Frame 
  8    Thread 0x7fffc7fff700 (LWP 26956) "texworks" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fffe2e67700 (LWP 26955) "QInotifyFileSys" 0x00007ffff4c42fbd in poll () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7fffd0fec700 (LWP 26954) "QInotifyFileSys" 0x00007ffff4c42fbd in poll () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7fffe3e69700 (LWP 26951) "gmain" 0x00007ffff4c42fbd in poll () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7fffe466a700 (LWP 26950) "gdbus" 0x00007ffff4c42fbd in poll () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7ffff7fc47c0 (LWP 26946) "texworks" 0x00007ffff625c8bc in 
QTextLine::textStart() const () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) thread
[Current thread is 1 (Thread 0x7ffff7fc47c0 (LWP 26946))]
(gdb) 

About the OS :
$ cat /etc/issue
Ubuntu 14.04 LTS \n \l
$ cat /proc/version
Linux version 3.13.0-24-generic (buildd@batsu) (gcc version 4.8.2 (Ubuntu 
4.8.2-19ubuntu1) ) #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014
$ uname -a
Linux bacata 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 
x86_64 x86_64 x86_64 GNU/Linux

Hope this will help.
```

Original issue reported on code.google.com by `mariepio...@gmail.com` on 23 May 2014 at 10:36

**Comment by stloeffler** [comment] 2016-03-17 13:30
Duplicate of #469

**Closed by stloeffler** 2016-03-17 13:30 UTC
Labels: auto-migrated, bug
