### ISSUE TITLE
TW crashed unexpectedly.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#593] opened 2015-03-14 11:05 UTC
```
What steps will reproduce the problem?
1. Open latex file.
2. Scroll down to the end of file.
3. Press up and down arrows a few times. Voila!

What is the expected output? What do you see instead?
No expected output per say. I just want to navigate in my tex file : ( Instead 
it just crashes with these error messages :

  Problem Event Name:	APPCRASH
  Application Name:	TeXworks.exe
  Application Version:	0.4.4.1003
  Application Timestamp:	4f9d69bc
  Fault Module Name:	TeXworks.exe
  Fault Module Version:	0.4.4.1003
  Fault Module Timestamp:	4f9d69bc
  Exception Code:	c0000005
  Exception Offset:	00764e30
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	8a3a
  Additional Information 2:	8a3ad166bc77cec34b2c6501cc9cad26
  Additional Information 3:	da01
  Additional Information 4:	da01e01c84f19df02d2e2eaaa7eac552

What version of the product are you using? On what operating system?
I am using Version 0.4.4 1.1003 on Windows 7

Please provide any additional information below.
Re entering error messages for redundancy's sake :

  Problem Event Name:	APPCRASH
  Application Name:	TeXworks.exe
  Application Version:	0.4.4.1003
  Application Timestamp:	4f9d69bc
  Fault Module Name:	TeXworks.exe
  Fault Module Version:	0.4.4.1003
  Fault Module Timestamp:	4f9d69bc
  Exception Code:	c0000005
  Exception Offset:	00764e30
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	8a3a
  Additional Information 2:	8a3ad166bc77cec34b2c6501cc9cad26
  Additional Information 3:	da01
  Additional Information 4:	da01e01c84f19df02d2e2eaaa7eac552
```

Original issue reported on code.google.com by `aravind....@gmail.com` on 30 Jul 2012 at 11:54

**Comment by stloeffler** [comment] 2016-03-17 12:06
Duplicate of #469

**Closed by stloeffler** 2016-03-17 12:06 UTC
Labels: auto-migrated, bug
