### ISSUE TITLE
TexWorks hanging when certain filepath listed in 'recently opened'

### ISSUE THREAD

**Issue by matthiasbaer** [TeXworks/texworks#928] opened 2021-03-16 21:14 UTC
**Bug description:**
TexWorks takes an eternity to start and is hanging/not responding. Bug is also well described here:
https://tex.stackexchange.com/questions/488208/texworks-takes-more-than-20-minutes-to-start/582499#582499?newreg=12705b3fef4540e5bea6686be4fefa0d
I also observe that it takes 25% CPU while starting, however it doesn't take 20min but only 5min.
After a (not responding) window pops up it takes another couple of minutes until syntax highlightning colors the text.

**Steps to reproduce the problem:**
It apparently depends on the file list in the 'recently opened' menu.
When opening a file in the win10 Explorer, I can navigate to the file either by
Z:\path\to\the\file.tex (Z: is actually a drive on a server)
or by 
\\\\servername\path\to\the\file.tex
When opening a file by double clicking it in an explorer window that shows \\\\servername\\.... in the path line everything is ok.
In the 'recently opened' menu the filename appears (just the filename!).
When opening a file by double clicking in an explorer window that shows Z:\\... in the path line, the described bug appears.
In the 'recently opened' menu you can see the 'normal filenames' (just the filename) and a new line with the now opened file, but with its whole path (but with \\\\servername... not the drive letter!). So the menu looks like this:
\\\\servername\path\to\the\file.tex
otherfile.tex
testfile.tex
...

Whenever such a line (\\\\servername\...) appears/makes it into this menu TexWorks won't start properly, is hanging and is basically unusable.

The problem can be solved by clearing the 'recently opened' file list and restarting TexWorks.
However after clearing the 'recently opened' history, after the next start up of TexWorks the filename that made problems is still in the list (in the example 'file.tex'), but without the whole path. So you have to clear the menu twice to get it completely empty.

**Expected behavior:**
Should work with any 'type' of filepath.

**General information:**
_TeXworks version_: V0.6.5 (MiKTex 21.2) (Qt framework v5.15.2)
_TeXworks obtained from_: part of MiKTex
_Operating system_: Win 10

**Additional information:**
I hope this helps and im glad that something like TexWorks exists! Keep up the good work!

**Comment by stloeffler** [comment] 2021-06-10 13:39
Duplicate of #904 that should (hopefully) be fixed in the latest development version. Please test.

**Closed by stloeffler** 2021-06-10 13:39 UTC
Labels: bug, duplicate
