### ISSUE TITLE
Problem between macOS and TeXworks v0.6.9

### ISSUE THREAD

**Issue by matteofg** [TeXworks/texworks#1064] opened 2024-10-07 09:29 UTC
Since the release of TeXworks **0.6.9** (Feb 2024), I have noticed several issues with the management/navigation of TeXworks windows.

Test performed on macOS Sonoma (v14) and Sequoia (v15)

**Steps to reproduce the problem:**

1. TeXworks Preferences > flag "Open corresponding PDF preview with TeX files" checked;
2. open any previously compiled `.tex` file.

**Issues encountered**

- the "Editor" window is the active window, but the menu bar corresponds to the "Preview" window;
- in this context the "text cursor" is not visible;
<img width="1022" alt="Screenshot 2024-10-07 at 10 12 09" src="https://github.com/user-attachments/assets/c8f2f720-58cf-4ceb-adb5-8c99d94b2607">

- closing the "Preview" window only the "TeXworks" drop down menu remains.
<img width="281" alt="Screenshot 2024-10-07 at 10 18 58" src="https://github.com/user-attachments/assets/af43f8c2-5760-42c7-96a9-87359beab495">

Ultimately, there is a problem between the active window and the menu bar.
The solution is to click on the "Preview" window and then re-click on the "Editor" window.
None of this happened with previous versions of TeXworks.

**Comment by jlaurens** [comment] 2024-10-07 09:54
Is it related to issue #1005 ?

**Comment by matteofg** [comment] 2024-10-07 11:23
> Is it related to issue #1005 ?

I would definitely say that the problem is the same.

**Comment by stloeffler** [comment] 2024-10-07 16:07
Which version of Qt is TeXworks using (you can check in the "About TeXworks..." dialog)? #1005 seems to only affect Qt 5.x, but the 0.6.9 build for macOS 11 and above uses Qt 6.5.3.

**Comment by matteofg** [comment] 2024-10-07 17:49
In the "About TeXworks" dialog I read: Qt application framework v5.15.2 by The Qt Company.

How is it possible to have an older version of Qt inside the latest version of TeXworks? Confused...

**Comment by stloeffler** [comment] 2024-10-07 19:08
There are two macOS builds of TeXworks 0.6.9: one for "recent" versions of macOS (11 and above) which uses Qt 6.5.3, and one for "legacy" versions of macOS (10.13 and above) which uses  Qt 5.15.2 (as Qt 6 doesn't support those older versions of macOS). Presumably, you are using the version for "legacy" macOS instead of the version for "modern" macOS.
I'm closing this for now as it seems to be a duplicate of #1005.

**Closed by stloeffler** 2024-10-07 19:08 UTC
Labels: bug
