### ISSUE TITLE
JPG-Images are not shown in Texworks preview

### ISSUE THREAD

**Issue by ulrich1a** [TeXworks/texworks#824] opened 2017-08-31 08:05 UTC
_Steps to reproduce the problem_:

1. Create a document with the package graphicx
2. includegraphics with a jpg-file
3. compile the document

_Expected output_: A preview with the jpg-file displayed

_Actual output_: A preview with a blank white rectangle instead

_TeXworks version_: 0.6.2 
_TeXworks obtained from_: MikTeX 2.9.6350 64-bit [r.7.ecce17, 29.04.2017
_Operating system_: Windows 10, 64bit

_Please provide any additional information below_:
Everything was ok with Texworks 0.6.1 in Windows 7 32-bit.
The created PDF has the image, so it is a previewer problem.
[mwe.zip](https://github.com/TeXworks/texworks/files/1266288/mwe.zip)

**Comment by ulrich1a** [comment] 2017-08-31 08:08
Forgot to say, that other image types work well like png and pdf.

**Comment by ashipunov** [comment] 2017-09-01 23:51
I cannot reproduce, everything works for me on Linux. But I think that I saw something similar long ago. Can you open this JPEG file in, saying, IrfanView and then save it again? In my case, it did help.

**Comment by stloeffler** [comment] 2017-09-02 09:50
Could you try with the latest version of TeXworks from [Bintray](https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest#files)? This might be related to how some of the libraries TeXworks uses are built, which might differ between the "official" and the MiKTeX build.

**Comment by uwemenzel** [comment] 2017-09-04 11:06
I have exactly the same problem: preview shows blank white space instead of the image. A symbol for a magnifying glass appears where the image should be. Update doesn't help. Windows 10, 64 bit. 
Disappointing.

**Comment by stloeffler** [comment] 2017-09-04 11:53
0.6.2 (MiKTeX 2.9.6400) [r.7ecce17, 29.04.2017 18:23] works fine for me on Windows 7 32bit with the posted MWE.
What's this magnifying glass symbol? Please post a screenshot.

**Comment by uwemenzel** [comment] 2017-09-04 15:06
Hi,
that was probably not important.
It is possible to switch between the hand tool and this magnifying glass by
clicking on the corresponding icon in the
menu bar of the preview window.
/uwe

**Comment by ulrich1a** [comment] 2017-09-05 10:15
I have tested two binaries from [Bintray](https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest#files), Latest Version  TeXworks-win-0.7-201709021552-git_3939d19.zip and TeXworks-win-0.6.2-201704300708-git_7ecce17.zip. These binaries are 32-bit and do work as expected with the MWE in Windows 10 64bit. So it seems, that the problem exist only in the 64bit-Version available from MikTex. What next?

Ulrich

**Comment by stloeffler** [comment] 2017-09-05 18:55
In that case: please report the problem to the MiKTeX devs. They are compiling TeXworks themselves (apparently also a native 64 bit version), and it seems that something went wrong there. IIRC, the poppler library build system changed some things regarding the handling of jpeg libraries - maybe something went wrong there, inadvertently disabling jpeg support on poppler altogether?
Anyway, I'm closing this issue for the time being as it seems to be a MiKTeX problem, not a problem with the code or build system used here.

**Closed by stloeffler** 2017-09-05 18:55 UTC
