### ISSUE TITLE
texworks compresses lines in view and crashes when navigating them

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#505] opened 2015-03-14 11:04 UTC
```
What steps will reproduce the problem?
1. Open large document
2. Find line where line numbering is printed multiple times over each other 
(see attachment. The line numbers 1333 and following and 1340 + 1341 are shown 
on the same line).
3. Put cursor into line with mouse.
4. Navigate upwards out of line with cursor keys
5. texwork crashes

What is the expected output? What do you see instead?
I'm expecting the cursor in to be shown in the line above.

What version of the product are you using? On what operating system?
I'm using texworks 0.4.1 r827 on Win7 professional 64bit en.

Please provide any additional information below.
I could not find a short bug-reproducing sample - all short samples work don't 
show the error. If I encounter such an example I will attach it to this issue.

This issue may somehow be related to issue 497, but I don't see there multiple 
line numbers in one line.

```

Original issue reported on code.google.com by `rastered...@gmail.com` on 7 Jun 2011 at 10:59

Attachments:
* [texworks_linenumberproblem.PNG](https://storage.googleapis.com/google-code-attachments/texworks/issue-505/comment-0/texworks_linenumberproblem.PNG)

**Comment by stloeffler** [comment] 2016-03-17 11:49
Duplicate of #469

**Closed by stloeffler** 2016-03-17 11:49 UTC
Labels: auto-migrated, bug
