### ISSUE TITLE
jump to source bug?

### ISSUE THREAD

**Issue by lowai** [TeXworks/texworks#738] opened 2016-04-15 05:26 UTC
Writing a paper with a main.tex, which include several other tex files. Whenever I choose 'jump to source' from the preview window, it always jumps back to the main.tex, rather than the actual position in the other tex files.

**Comment by stloeffler** [comment] 2016-04-21 18:00
Looks like a duplicate of #736 which was fixed in bbd405d

**Closed** 2016-05-05 06:36 UTC
Labels: bug, duplicate
