### ISSUE TITLE
Pictures/diagrams not shown up in Texworks PDF viewer

### ISSUE THREAD

**Issue by tluocs** [TeXworks/texworks#984] opened 2022-11-28 21:21 UTC
JPG does not show up, PDF pictures only show annotated text and the rest is just blank. (Very simple latex command with \includegraphics).

The generated PDF file does contain all the pictures and can be viewed in any other PDF viewer such as Acrobat or Mac Preview. Just that those pictures are not shown in Texworks' own PDF viewer.

**Comment by stloeffler** [comment] 2022-12-26 16:27
Thanks for reporting. To better understand your issue, please provide some additional info.

* Which version of TeXworks are you using?
* Where did you get it from?
* Which operating system are you using (and which version of it)?
* Please provide one or two example images that don't work

**Comment by tluocs** [comment] 2022-12-27 01:57
* TeXworks version: Version 0.6.7 ("github") [r.23c4c74, 2/26/22 5:03 AM]
* Where: Official TeXworks website
* OS: macOS Monterey, version 12.6 (21G115)
* Example images: 4 examples are attached.

**Comment by stloeffler** [comment] 2022-12-27 07:00
Thanks for the quick reply. Unfortunately, the images didn't get through to Github, but I believe that this issue is a duplicate of #975 (see there for more details) and has already been fixed in the latest development version.

**Closed** 2022-12-27 07:01 UTC
Labels: bug, duplicate, Mac OS X
