### ISSUE TITLE
Texworks taking long time to start and freezing

### ISSUE THREAD

**Issue by UweZiegenhagen** [TeXworks/texworks#904] opened 2020-07-30 18:14 UTC
For a few weeks now I am experiencing TeXworks to start extremely slowly,  according to some other user on the TeX Live mailing list I am not the only one.

**Steps to reproduce the problem:**

1. Run TeXworks.exe
2. No GUI appears
3. Task manager shows a load of 15%--18% (on an i7 with 32 GB RAM)
4. After around 7 minutes the GUI appears, load goes to nearly 0.
5. Deleting the %userhome%/Texworks directory does not improve the situation

**General information:**
_TeXworks version_:  0.6.5
_TeXworks obtained from_:  TeX Live 2020
_Operating system_:  Windows 10

**Additional information:**

**Comment by stloeffler** [comment] 2020-07-31 08:11
Thanks for reporting and sorry for the inconvenience. A few questions:
* as I understand it, this problem occurs only/predominantly on Win 10, but not on Win 7?
* am I correct in assuming that 15%-18% correspond to approx. 1 CPU core (i.e., do you have a hexacore i7?)
* does this problem occur also with the latest development version (obtainable from https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest/view - there should be no problem running this side-by-side with the TL version, just put it in its own directory and don't overwrite the TL binary)?
* what paths are shown under Edit > Preferences > Typesetting?
* what is shown under Help > Settings and Resources...?
* what versions (of Tw and Qt) are shown under Help > About TeXworks...?

Some background: there is not very much Tw does during startup. Loading settings is one thing, of course, but that shouldn't be resource intensive. One thing that has caused some issues in the past was checking which typesetting tools are available. This requires crawling through directories (as given in the preferences), which may take some time; although it should not amount to several minutes. Another thing that has caused some problems in the past was spellchecking and highlighting huge documents, but that does not occur if you run Tw without opening a file in it. It may also be related to something in the underlying Qt framework, which could make it hard to track down, however.

**Comment by UweZiegenhagen** [comment] 2020-07-31 08:25
Cleaning the registry might help, I'll try later today.

https://tex.stackexchange.com/questions/488208/texworks-takes-more-than-20-minutes-to-start

**Comment by khzimmer** [comment] 2020-07-31 17:34
I cannot test on Windows here right now, so I am just guessing: Might the reason be in these lines of **TWUtils.cpp** which is called during start-up when the application created the menu list of recently used files?

QString TWUtils::strippedName(const QString &fullFileName, const unsigned int dirComponents /* = 0 */)
{
	QDir dir(QFileInfo(fullFileName).dir());
...

Might it be that this code has a too long timeout, if a file was stored in settings that was on a drive that is not present while the application starts?

**Comment by gnw3** [comment] 2020-08-01 15:17
TeXworks from TeX Live 2020 with current updates has been working for me on Windows 10, but after seeing the report of this problem, I tried TeXworks on MiKTeX (also current, using a per-user installation) and 1) it took a very long time to load, and 2) every action gave "Not Responding" in the header bar.  Deleting `Computer\HKEY_CURRENT_USER\Software\TUG\TeXworks` restored normal operation.  One of the recent files was on a network server that was not available during the test.

**Comment by RickVoland** [comment] 2020-08-02 01:00
I still have the similar problem:  TeXlive 2020, Windows 10, 64-bit, The installed TeXworks takes a very long time to open or close a file while using 25% CPU.  It's an i7 CPU with 2 physical cores.  I tried the suggestions about deleting the suggested registry keys, but that did not resolve the issue.  I downloaded 2 recent versions of TeXworks and put the files for each one in its own folder on the desktop.  
TeXworks-win-0.7-202006210838
and
TeXworks-win-0.6.5-202003251917-git_649699a
each works just fine, starts quickly, and edits just fine. 
It's the installed version of TeXworks that has trouble.
The problem started after I ran TeXlive updates on Friday, July 24.

TeXworks still runs fine on Windows 7, but I didn't run those updates.

**Comment by stloeffler** [comment] 2020-08-02 08:23
Thanks for testing. It seems that this problem relates to network drives. To narrow things down:
* Could someone (who experiences this issue) try with just deleting the `recentFiles` key?
* Could someone (who experiences this issue) try with just deleting the `openDialogDir` key?
* Could someone (who does not - or no longer - experience this issue) try to open a file on an external hard disk (e.g. a USB drive), then remove the drive and restart Tw?
* Could someone (who does not - or no longer - experience this issue) try to open a file on a mapped network drive (one that has a drive letter), then unmap the drive and restart Tw?
* Could someone (who does not - or no longer - experience this issue) try to open a file from "My network places" (without mapping it to a drive letter), then disconnect from the respective network and restart Tw?

@khzimmer yes, the code lines you mentioned are a very likely candidate for the cause of the issue. The docs don't mention that the file is actually accessed for the things we need (mostly path manipulations), but maybe this still happens under the hood. I'll have to look into this.

@RickVoland Can you confirm that the "recent files" list (under File > Open Recent) is the same for the TeXLive installation and the manually downloaded ones? The reason is that the TeXLive version may have some modifications (e.g. to where settings are stored) which may cause additional differences.

**Comment by RickVoland** [comment] 2020-08-02 20:46
I think the problem on my machine is not caused by network drives because I can entirely reproduce the problem using *.tex files on my desktop.  Microsoft OneDrive and Adobe Creative Cloud are installed on this computer, but contain nothing.  I verified before and after the actions below.  
I created a file test-letter.tex from the letter template and a file test-xetex from the xetex article template.  I opened them separately with the TeXworks installed with TeXlive 2020, and with TeXworks 0.65 and TeXworks 0.70 that are located in separate folders on my desktop (as indicated previously).  The installed TeXworks shows one list of "recent files."  The TeXworks 0.65 and TeXworks 0.70 located in separate folders on the desktop both display the same list of "recent files", and this list is different from the "recent files" for the TeXworks installed with TeXlive.  
It looks like the TeXworks installed with TeXlive has configuration files at 
~\.texlive2020\texmf-config\texworks
The two versions of TeXworks in folders on the desktop have configuration files at
~\TeXworks
I infer this based on how the date stamps change for these folders and subfolders when I run the different versions of TeXworks.

**Comment by RickVoland** [comment] 2020-08-02 20:48
Just to be clear--all those *.tex test files are on my desktop.

**Comment by gnw3** [comment] 2020-08-03 14:43
I could not reproduce the problem 3 versions of TeXworks on a laptop with Windows 10 Enterprise 10.0.16299 that hasn't been on any network since March (airplane mode).  This is a much older version of Windows 10 than the one that exhibited the problem.

### CTAN Version 0.6.5 r.649699a (downloaded .zip file)

System in "airplane" mode; Recent files list includes files on a network server that is not reachable. There was not large delay.

### TeX Live 2020 (last updated March, 2020) Version 0.6.4 ("travis-ci") r.982c11c, 3/15/2020 7:03 AM)

"recent files" has only one entry

### MiKTeX Version 0.6.3 (MiKTeX 2.9.7300) [r.a2470cac, 3/16/2019 2:06PM)

Delay of under a minute loading.  Recent files list matches the list used by the CTAN version.

I also tried the removable USB key, system policy makes the key "read-only".

**Comment by RickVoland** [comment] 2020-08-26 18:31
Maybe the problem is related to MS-Windows Defender.
I have a second computer, this one still running Windows 7 where I only allow minimal updates like Windows Defender.  TeXworks was running just fine until a recent update of Windows Defender.  Now, it has the same slowness for TeXworks that I describe above for my first computer under Windows 10.

**Comment by stloeffler** [comment] 2020-08-29 08:46
@RickVoland From your comment before, I take it that both 0.6.5 and 0.7 downloaded from GitHub work fine (or at least used to work fine), but the one installed by TeXLive does not? If that's the case I suspect that there is something different with the TeXLive version (maybe something about the configuration, startup scripts, or whatever). In that case, it would probably be best to report the issue to the TeXLive devs...

@RickVoland @gnw3 It is possible that Windows Defender (or some other Windows component) has something to do with this... Maybe they are suspicious of TeXworks (which is currently not signed because of the cost and extra complications during compilation connected to it). Maybe they are scrutinizing Tw extensively during runtime. Maybe it's a virus scanner. One way of finding out is to temporarily disable all potentially problematic components (at your own risk ;)). In any case, if it is indeed caused by a Windows component/update, it should probably affect all Tw versions in pretty much the same way (so either all versions experience the problem or none).

For reference, Tw starts in <1s on my Linux laptop.

**Comment by RickVoland** [comment] 2020-08-29 17:40
Thanks for the responses.  You are correct.  Both 0.6.5 and 0.7 work just fine when executed from the desktop of my Windows 10 laptop.  The version of TeXworks installed by TeXlive 2020 has issues both on Windows 10 and now also on Windows 7.  The problems are only for the version installed by TeXlive in its normal location.    
Thanks,

**Comment by gnw3** [comment] 2020-08-29 19:43
I have not been able to reproduce the issue since my initial report, so I wonder if it was a Windows bug that has been patched, but I have not tested using a network drive that goes offline.

There some reports of long startup times another application (ESA SNAP) on systems with Windows Defender.  Dell recently added  [Is your system locking up during Windows Defender scans?](https://www.dell.com/support/article/en-ca/sln308113/windows-defender-resolving-high-hard-disk-drive-and-cpu-usage-during-scans?lang=en) with explanations and diagnostic hints.

I did investigate the differences between TeX Live Texworks and MiKTeX's version.   [TeX Live avoids the Windows registry](https://tug.org/pipermail/texworks/2011q1/003997.html), so a user's recent files list is stored in `%USERPROFILE%\.texlive2020\texmf-config\texworks\TUG\TeXworks.ini`.   Interestingly, ESA SNAP also stores the recently used list under `%USERPROFILE%`.

**Comment by stloeffler** [comment] 2020-09-21 07:41
Searching the internet suggests that this may indeed be a Windows problem (that comes and goes with updates) and may be related to NetBIOS and/or SMB configuration. See e.g. https://community.spiceworks.com/topic/2168064-why-is-windows-10-very-slow-to-open-network-files

**Comment by Theo-de** [comment] 2021-01-23 11:22
Ha - perfect reference, from edocevoli - that's it!! You guys are doing a great job!
Unter issue #904 I tried out stloeffler's advice: "Could someone (who experiences this issue) try with just deleting the **recentFiles** key?"
After having done this, TexWorks starts again quickly  in user mode (3-4 seconds) and can open (and run) tex-files again.
So I'm a happy camper again.

**Comment by matthiasbaer** [comment] 2021-03-16 21:34
I recently opened a new issue/bug report because I didn't see this one. I'm sorry for that.
However in the new bug report I describe how I can reproduce the error. For my case the files are always (!) located on a server, but it makes a difference if I browse (in the win explorer) to the files by
Z:\\... (Z: is a 'link' to the same server)
or
\\\\servername\\...
and double clicking.
Maybe that helps. I can avoid this problem by 'carefully' browsing to my files...

**Comment by stloeffler** [comment] 2021-04-06 15:34
I have recently fixed some potential issues with the construction of unique labels in the recent files list. Could someone please test if this affects (solves?) this issue as well? Any builds dated April 6, 2021 (which should be available a few minutes after this comment is posted) or later should work.

**Comment by stloeffler** [comment] 2022-02-20 22:22
This should finally be fully resolved by 16a6daf

**Closed by stloeffler** 2022-02-20 22:22 UTC
Labels: bug

**Comment by RickVoland** [comment] 2022-02-20 23:32
Thanks for the information. TeXworks is fine again. 

What got it to work was renaming 
C:\Users\Rick\.texlive2021\texmf-config\texworks\TUG\TeXworks.ini 
to have it recreate this file. 

Thanks, 

Rick Voland 
***@***.***
