### ISSUE TITLE
TW crashes when scrolling down in soruce win (spellchecker problem?1)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#613] opened 2015-03-14 11:05 UTC
```
What steps will reproduce the problem?

1. open a .tex file
2. scroll down in source win using page-down-key or arrow-key 
3. when you reach the end of the file TW shuts down (sometimes also when just 
scrolling around)

---> when I deactivate spell checker (de_CH_frami), TW doesn't crash. Perhaps 
it's hunspell related?

What is the expected output? What do you see instead?

it crashes ;-)

What version of the product are you using? On what operating system?

TW 0.5 r.1007 (Debian) on Ubuntu 12.10 (Unity)

Please provide any additional information below.

```

Original issue reported on code.google.com by `tj.schwe...@gmail.com` on 6 Feb 2013 at 9:16

**Comment by stloeffler** [comment] 2016-03-17 13:13
Duplicate of #469

**Closed by stloeffler** 2016-03-17 13:13 UTC
Labels: auto-migrated, bug
