### ISSUE TITLE
Interface Font size is too small

### ISSUE THREAD

**Issue by nicholasandrzej** [TeXworks/texworks#986] opened 2023-01-13 16:43 UTC
**Bug description:**
I can control the font size of the documents, but the font size of the labels and every menu window is unreadably small and none of the font options under preferences or format change the size. Any help is appreciated.

**General information:**
_TeXworks version_: 0.6.7 (MiKTeX 22.12)
_TeXworks obtained from_: MiKTeX
_Operating system_: Windows 11

**Comment by stloeffler** [comment] 2023-01-14 10:07
Thanks for reporting. Unfortunately, I don't have Windows 11 to test, but on my Windows 10 setup everything seems to work as expected. To try to narrow down the problem further, please:
* Try the latest development version for Windows 10 and above ([link](https://nightly.link/TeXworks/texworks/workflows/cd/main/TeXworks-Windows10))
* Provide additional information about you setup, in particular:
  - Are you using an external monitor?
  - What are the resolution (in px), physical size (typically the diagonal in inches), and/or the dpi of your display?
  - If you are using multiple screens, does the problem occur on all screens?
* Attach relevant screenshots

**Comment by stloeffler** [comment] 2023-01-22 21:24
Thanks for the screenshots. I'm glad to hear that the latest development version works (better). 

A few observations:
* In the windows in the background, the menu text ("File", "Edit", ...) seems much larger than all other text (the title bar, the icon labels, the status bar). Judging by the grey bar, which I assume is the highlighted current line, the same goes for text entered in the editor. Is this correct and intentional?
* The menu font and current line size seem more reasonable (i.e., in line with the window title bar) in the (old/problematic) foreground window. Although the icons seem a bit too large (though this can be changed in the preferences) and the item labels much too small...
* The "Package installation" dialog is produced by MiKTeX, not by TeXworks. Could you check if running some of the MiKTeX maintenance tools/package manager directly (from the start menu) also results in the font size problem? (if so, at least that part is a MiKTeX problem and should be reported to its developers; if not, i.e. if the problem only occurs when the dialog is opened by TeXworks, the issue is probably in some problematic settings inherited from the TeXworks process)
* Can you confirm that the old/problematic version was using Qt 5.x while the development version was using Qt 6.x (from Help > About TeXworks...)?

**Comment by stloeffler** [comment] 2023-10-22 11:03
Closing as the current (development) version seems to work as expected, and there was no further activity.

**Closed by stloeffler** 2023-10-22 11:03 UTC
Labels: bug
