### ISSUE TITLE
No undo/redo after typesetting with Google Drive File Stream

### ISSUE THREAD

**Issue by TheCarlWinslow** [TeXworks/texworks#901] opened 2020-06-13 04:29 UTC
**Bug description:**
When editing a file on Google Drive File Stream, the ability to undo or redo disappears completely after typesetting completes. With 0.6.4 and 0.6.3 (and probably further back), undo and redo work perfectly fine in the same setting.

**Steps to reproduce the problem:**
1. Create new file from template -> Basic LaTeX documents -> article.tex
2. Save it somewhere on your Google Drive File Stream
3. Make any edit and then typeset. You can no longer undo any changes; the option is grayed out in the menu.

**Expected behavior:**
The ability to undo should still be there after typesetting, as it used to be.

**General information:**
_TeXworks version_: 0.6.5-202003252107
_TeXworks obtained from_: https://github.com/TeXworks/texworks/releases/tag/release-0.6.5
_Operating system_: Windows 10

**Additional information:**
This is a real workflow-killer. Working directly on the Google Drive File Stream makes cloud backup and cloud share across devices an afterthought. Now my only option is to work off of my local drive and then manually move things back and forth to the Google Drive; or to stick with TexWorks 0.6.4 (I have chosen the latter).

**Comment by stloeffler** [comment] 2020-06-13 06:14
Thanks for reporting this.
First of all, nothing undo/redo-related has changed in the Tw code since 0.6.4 (in fact, the undo/redo feature relies almost completely on the underlying Qt framework). It is also not related to typesetting in any way.
That said, Tw does save a file if it was modified before typesetting. Tw also reloads a file if it has changed on disk and was not changed in Tw. So if you have unsaved changes when you hit typeset, it could be that Tw saves those changes, but the cloud synchronization process takes some time. Thus, in the end, it looks as if the file was saved to disk later than Tw saved it, and therefore it is reloaded, effectively destroying the undo/redo cache. FWIW, the same behavior was in 0.6.4, but obviously this may be affected by timing issues, e.g., in the underlying Qt framework.
A possible solution would be to not reload the document if it is identical. But first, I'd like to confirm that my reasoning is correct. So:

* Is it correct that you didn't save your changes before hitting typeset?
* Does the same problem occur if you simply save changes, but don't typeset?
* Does it occur if you save your changes, and then hit typeset?

(Note that typesetting does obviously result in many (other) file changes on the Google Drive, so that could contribute to the issue if synchronizing those changes is pooled somehow).

**Comment by TheCarlWinslow** [comment] 2020-06-13 11:53
> Is it correct that you didn't save your changes before hitting typeset?

Correct.

> Does the same problem occur if you simply save changes, but don't typeset?

I get a different issue when I save without typsetting. The following query pops up in both 0.6.4 and 0.6.5:
![image](https://user-images.githubusercontent.com/66506239/84567724-576c3980-ad2f-11ea-8dca-cd1bc2b777e8.png)
Undo/redo still work regardless of whether I select OK or Cancel, as long as I don't typeset it. (This popup doesn't show in 0.6.3.)

> Does it occur if you save your changes, and then hit typeset?

Undo/redo work after saving, but then the subsequent typeset will erase undo/redo.

So it seems something about the way saving relates to Google Drive File Stream changed from 0.6.3 to 0.6.4; and something about the way typesetting relates to Google Drive File Stream changed from 0.6.4 to 0.6.5.

**Comment by stloeffler** [comment] 2020-06-13 20:02
Thanks for testing. This pretty much confirmed my theory. The dialog box you mention is shown when the modification time of the file on the disk does not match the last time Tw saved the document.
Actually, it has been around since 2008, but maybe something about detecting whether or not a file was modified has changed in the different versions of Qt the various versions of Tw were built with.
Anyway, could you try the latest development build from [Bintray](https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest/view) - it should be labeled 0.7-20200613 or later - hopefully the issue is fixed now.

**Comment by TheCarlWinslow** [comment] 2020-06-14 08:05
Undo/redo history is maintained after typesetting with the dev build. Great!

The "File changed on disk" query pops up almost every time, however, which slows down workflow because typesetting requires an extra two keystrokes or mouse click. Something like a "Remember this answer" option could take care of that.

**Comment by stloeffler** [comment] 2020-06-15 20:22
With the newest version (dated 20200615 or later), the constant popup boxes should be gone as well.

**Comment by TheCarlWinslow** [comment] 2020-06-16 06:43
Perfect, thank you!

**Comment by TheCarlWinslow** [comment] 2020-06-17 11:50
Well, another related issue has revealed itself with use: if typesetting encounters some error (e.g. mismatched curly brackets), then the "File Changed On Disk" query pops with subsequent saving/typesetting. This isn't as egregious of a workflow killer, but maybe it's something you'd consider an issue nonetheless.

**Comment by stloeffler** [comment] 2020-06-18 09:01
Hm, to (hopefully) understand what's going on, could you please be more specific about the exact sequence of steps (and messages)? Is your workflow something like as follows?
1. You create a document with an error (say, it contains just the letter "a")
2. Do you save it manually, or do you hit "typeset"?
3. Typesetting runs and stops with an error. Do you then abort the typesetting or start modifying the document before killing the typesetting process?
4. Do you at any point see the message "File ... loaded" in the status bar, indicating that TeXworks has detected that the file on disk has changed and reloaded it?
5. When does the warning message appear? When you save manually? (with the old typesetting process still running? with it being killed already?) When you kill the previous typesetting process (after having modified the document)? When starting the new typesetting process (with or without having saved manually before)?
6. Which warning message do you see, exactly? (There is one saying "Do you want to discard your current changes, and reload the file from disk?" and one saying "Do you want to proceed with saving this file, overwriting the version on disk?"; I take it you see the latter?)

Reopening this issue for now until we figure out how to proceed with this.

**Comment by TheCarlWinslow** [comment] 2020-06-23 13:18
Sorry for the delay. I do have an update that might be informative, however. 

The issue is not present when I use the default "pdfLaTeX" processing tools. However, when I use "pdfLaTex+MakeIndex+BibTeX" as given in the MiKTeX distribution, the issue appears only if there are too many characters in the preamble. Removing the argument --clean makes the issue go away. (I am not sure what the implications are for removing the argument.) 

When --clean is left in as an argument, the issue can be replicated in the following way.

1. Typeset the following document. 
![error](https://user-images.githubusercontent.com/66506239/85407990-cb20fa00-b518-11ea-92f7-d7d3329f9906.png)
2. Add some error. Easiest way it to just put a single $ in the document area.
3. Typeset and it will fail.
4. Remove the $ and try to typeset again, which gives popup 
![filechanged](https://user-images.githubusercontent.com/66506239/85408121-f73c7b00-b518-11ea-964f-1d218555a1e5.png)

There are 442 instances of % in the preamble. Remove even a single % and the popup no longer appears.

**Comment by stloeffler** [comment] 2021-06-10 14:01
Sorry for the very late reply.
It seems that this might be a MiKTeX issue, then (seeing that it only seems to occur when using the MiKTeX-specific addition of "pdfLaTeX+MakeIndex+BibTeX").
For reference, ``--clean`` should "Remove all auxiliary files." [Source](https://docs.miktex.org/manual/texify.html). What it really does seems to be to typeset everything in a temporary directory? [Source](https://github.com/MiKTeX/miktex/blob/next/Programs/MiKTeX/texify/mcd.cpp#L1739-L1745). Maybe this entails copying/rewriting/accessing files in a way that makes Google Drive unhappy?

There seems to be a hidden debug feature of `texify` by specifying `--debug` [Source](https://github.com/MiKTeX/miktex/blob/next/Programs/MiKTeX/texify/mcd.cpp#L1849) that might print additional information (e.g., which files are accessed/copied/moved in which directories). I'm not sure if it's available in the distributed binaries, but if it is, it might help shed some light on this issue.

**Comment by stloeffler** [comment] 2022-04-16 19:12
Closed as it seems to be a MiKTeX-specific issue, not a general TeXworks issue.

**Closed by stloeffler** 2022-04-16 19:12 UTC
Labels: bug
