### ISSUE TITLE
Windows Symbolic Directory Links

### ISSUE THREAD

**Issue by wollmich** [TeXworks/texworks#753] opened 2016-09-14 09:39 UTC
_Steps to reproduce the problem_:
1. Let's assume you have \server1\share1 and \server2\share2
2. Let's assume you have a symbolic directory link on server1. mklink /d \server1\share2link \server2\share2
3. Open a text document (\server1\share2link\test.tex)
4. Typeset 

_Expected output_:
Show PDF preview

_Actual output_:
Root document is not readable.

_TeXworks version_: 0.6.1
_TeXworks obtained from_: http://miktex.org/
_Operating system_: Windows 7 Enterprise 64 bit

_Please provide any additional information below_:
We don't want to use server2 directly because we don't want to change our directory structure. With all other programs this is not issue.

**Comment by stloeffler** [comment] 2016-10-17 21:04
Unfortunately, I couldn't reproduce this problem on my machine.
 * Do I understand your report correctly that typesetting does not work (as opposed to a pdf file being created by the pdf previewer not finding the file)?
 * When you open the tex file via File > Open, does entering \server1\share2link take you to \server2\share2 (literally switching to the share on server2, not just displaying its contents under the "label" of server1)?
 * When you create a new typesetting tool with Program="echo" and Arguments="$fullname" (see also [AdvancedTypesettingTools](https://github.com/TeXworks/texworks/wiki/AdvancedTypesettingTools)) and use that, what's the output (it should be the path to your root file, without any typesetting; you may need to manually show the console via Windows > Show Console Output).

**Comment by wollmich** [comment] 2016-10-26 15:39
Hi,

 

Let’s assume I’ve a simple tex document on server2. So I’ve two ways to access it.

1.       \server1\share2link\test.tex

2.       \server2\share2\test.tex

 

> Do I understand your report correctly that typesetting does not work (as opposed to a pdf file being created by the pdf previewer not finding the file)?

 

1.       Typeset is not working. PDF previewer can’t find file

2.       Typeset and PDF preview is working.

 

> When you open the tex file via File > Open, does entering \server1\share2link take you to \server2\share2 (literally switching to the share on server2, not just displaying its contents under the "label" of server1)?

 

No it’s showing the contents of server2 under the share2link of server1.

 

> When you create a new typesetting tool with Program="echo" and Arguments="$fullname" (see also AdvancedTypesettingTools) and use that, what's the output (it should be the path to your root file, without any typesetting; you may need to manually show the console via Windows > Show Console Output).

 

Console output using echo:

1.       There is nothing written to the console output. Status: Root document is not readable.

2.       \\server2\share2\test.tex <file:///\\server2\share2\test.tex>  <-- ok

 

Regards

**Comment by stloeffler** [comment] 2022-04-30 06:29
I finally managed to reproduce this issue with the mentioned TeXworks version (0.6.1), but it seems to be resolved in the latest stable version (0.6.7). Closing.

**Closed by stloeffler** 2022-04-30 06:29 UTC
Labels: bug, Windows

**Comment by wollmich** [comment] 2022-05-02 06:47
I did as well a test on my side with Version 0.6.5 and it works as well.
