### ISSUE TITLE
Log Parser misses some errors

### ISSUE THREAD

**Issue by Markvy** [TeXworks/texworks#730] opened 2016-03-19 06:03 UTC
_Steps to reproduce the problem_:
Compile the following document:

```
\documentclass[12pt]{report}
\usepackage{hyperref}
\usepackage{lipsum}
\title{Log Parser is Great (When it Works)}
\author{Me}
\begin{document}
\lipsum[1]
\maketitle
\lipsum[2]
\begin{abstract}
\lipsum[3]
\end{abstract}
\lipsum[4]
\end{document}
```

_Expected output_:
The console shows a few warnings, due to the fact that this is a five page document, and all five pages are numbered "1".  But the Log Parser misses all of them
_Actual output_:
The Log Parser should catch these?  Maybe?
_TeXworks version_: 0.4.5
_TeXworks obtained from_: MikTeX
_Operating system_: Win10

**Comment by stloeffler** [comment] 2016-03-19 14:19
Thanks for finding! In fact, this seems to be a very low-level warning (issued by the TeX engine itself) which might be difficult to parse (because of it's lack of consistent formating).

@antoniomacri: The most pathological case I could come up with is the following where `pdfTeX warning` is broken in the middle (presumably it could even be broken inside a word, but that depends on whatever comes before in the log). Note that a similar error occurs with `LuaTeX warning`, but apparently not with `XeTeX`.

```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./untitled-file-00000000000001.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9l> and hyphenation patterns for 9 languages loaded.
(/usr/local/texlive/2015/texmf-dist/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2015/texmf-dist/tex/latex/base/size12.clo))
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2015/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2015/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2015/texmf-dist/tex/latex/lipsum/lipsum.sty)
(./untitled-file-00000000000001.aux)
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(./untitled-file-00000000000001.out) (./untitled-file-00000000000001.out)
[1{/usr/local/texlive/2015/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]pdfTeX
 warning (ext4): destination with the same identifier (name{page.1}) has been a
lready used, duplicate ignored
<to be read again> 
                   \relax 
l.9 \lipsum
           [2] [1]pdfTeX warning (ext4): destination with the same identifier (
name{page.1}) has been already used, duplicate ignored
<to be read again> 
                   \relax 
l.10 \begin{abstract}
                      [1]pdfTeX warning (ext4): destination with the same ident
ifier (name{page.1}) has been already used, duplicate ignored
<to be read again> 
                   \relax 
l.12 \end{abstract}
                    [1]pdfTeX warning (ext4): destination with the same identif
ier (name{page.1}) has been already used, duplicate ignored
<to be read again> 
                   \relax 
l.14 \end{document}
                    [1] (./untitled-file-00000000000001.aux) )
(see the transcript file for additional information)</usr/local/texlive/2015/te
xmf-dist/fonts/type1/public/amsfonts/cm/cmbx12.pfb></usr/local/texlive/2015/tex
mf-dist/fonts/type1/public/amsfonts/cm/cmr12.pfb></usr/local/texlive/2015/texmf
-dist/fonts/type1/public/amsfonts/cm/cmr17.pfb>
Output written on untitled-file-00000000000001.pdf (5 pages, 38532 bytes).
Transcript written on untitled-file-00000000000001.log.
```

Maybe we should try to unwrap the log before processing it. That would make many things (including filename parsing) a lot easier, unless it breaks some of the other patterns. I was thinking about something like `remove \n if it is char nr. max_print_line+1 and the next line does not start with \n`.

**Comment by UniqMartin** [comment] 2016-03-19 15:22
> Maybe we should try to unwrap the log before processing it.

Wouldn't it be cleaner (and much easier to get right) to avoid the wrapping in the first place instead of attempting to reverse it (which will always be somewhat fragile)?

To that end, TeXworks could set `max_print_line` in its environment to some sufficiently large value before invoking the typesetting tool. (I'm drawing my knowledge from [this StackExchange](http://tex.stackexchange.com/questions/52988/avoid-linebreaks-in-latex-console-log-output) answer.) E.g., on my OS X system, `max_print_line=1000 pdflatex test.tex` outputs for the given test document (and the `test.log` contents are similarly affected):

```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2016/02/01>
Babel <3.9n> and hyphenation patterns for 80 languages loaded.
(/opt/texlive/2015/texmf-dist/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/opt/texlive/2015/texmf-dist/tex/latex/base/size12.clo)) (/opt/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty (/opt/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty (/opt/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty)) (/opt/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty) (/opt/texlive/2015/texmf-dist/tex/generic/ifxetex/ifxetex.sty) (/opt/texlive/2015/texmf-dist/tex/latex/oberdiek/auxhook.sty) (/opt/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty) (/opt/texlive/2015/texmf-dist/tex/latex/hyperref/pd1enc.def) (/opt/texlive/2015/texmf-dist/tex/latex/latexconfig/hyperref.cfg) (/opt/texlive/2015/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/opt/texlive/2015/texmf-dist/tex/latex/hyperref/hpdftex.def (/opt/texlive/2015/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)) (/opt/texlive/2015/texmf-dist/tex/latex/lipsum/lipsum.sty) (./test.aux) (/opt/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty (/opt/texlive/2015/texmf-dist/tex/generic/oberdiek/gettitlestring.sty)) (./test.out) (./test.out) [1{/opt/texlive/2015/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has been already used, duplicate ignored
<to be read again>
                   \relax
l.9 \lipsum
           [2] [1]pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has been already used, duplicate ignored
<to be read again>
                   \relax
l.10 \begin{abstract}
                      [1]pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has been already used, duplicate ignored
<to be read again>
                   \relax
l.12 \end{abstract}
                    [1]pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has been already used, duplicate ignored
<to be read again>
                   \relax
l.14 \end{document}
                    [1] (./test.aux) )
(see the transcript file for additional information)</opt/texlive/2015/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx12.pfb></opt/texlive/2015/texmf-dist/fonts/type1/public/amsfonts/cm/cmr12.pfb></opt/texlive/2015/texmf-dist/fonts/type1/public/amsfonts/cm/cmr17.pfb>
Output written on test.pdf (5 pages, 38532 bytes).
Transcript written on test.log.
```

**Comment by Markvy** [comment] 2016-03-23 18:44
It seems to me that the reason this is so hard is not just line wrapping.  If the warning message BEGAN with a newline, then even at 80 chars, it would always be wrapped at a consistent place, with more than enough context to identify it.  Thus it seems to me that rather than trying to get LogParser to work around this mess, someone should submit a bug report to the maintainers of pdftex.  It looks like it's somewhat actively maintained, within a year or two, a new version is likely to come out and then this should be easy to fix.

**Comment by antoniomacri** [comment] 2017-11-05 16:44
Sorry for the laaaaate reply (maybe I would have better noticed an issue in my repository, https://github.com/antoniomacri/texworks-logparser).

I tried fixing this issue and committed a new version of the [logparser](https://github.com/antoniomacri/texworks-logparser).

However, I have not used a regex that recognizes the line number ("l.xx"), since it is not always present and trying to catch it can lead to errors.

Looking on the Internet, there are many different cases. Some warnings are terminated by an empty line:
```
pdfTeX warning (dest): name{subsubsection.1.0.14} has been referenced but does 
not exist, replaced by a fixed one

pdfTeX warning (dest): name{subsubsection.1.0.13} has been referenced but does 
not exist, replaced by a fixed one
```

Other logs are more complex:
```
pdfTeX warning: (null) (file C:/Users/Cinar/Documents/murat_cinar/ITU/Lectures/
PET504E/Notes/Transient_phenomena.pdf): PDF inclusion: found PDF version <1.6>,
 but at most version <1.4> allowed
<Transient_phenomena.pdf, id=8, 614.295pt x 794.97pt>
File: Transient_phenomena.pdf Graphic file (type pdf)

<use Transient_phenomena.pdf>
Overfull \hbox (113.59657pt too wide) in paragraph at lines 104--105
 [] 
 []
```
or
```
pdfTeX warning: pdflatex.EXE (file ../files_simview/pendulum/graphics/pendulum.
pdf): PDF inclusion: found PDF version <1.6>, but at most version <1.5> allowed


<../files_simview/pendulum/graphics/pendulum.pdf, id=2722, 252.88779pt x 166.47
726pt>
File: ../files_simview/pendulum/graphics/pendulum.pdf Graphic file (type pdf)
 <use ../files_simview/pendulum/graphics/pendulum.pdf>
Package pdftex.def Info: ../files_simview/pendulum/graphics/pendulum.pdf used o
n input line 20094.
(pdftex.def)             Requested size: 302.26375pt x 198.82166pt.
 [405] [406 <../files_simview/pendulum/graphics/pendulum.pdf>] [407] [408]
Overfull \hbox (0.62843pt too wide) detected at line 20288
[] \OT1/cmr/m/n/10.95 = [] [] + [] []
 []
```

In [this question on TeX Stack Exchange](https://tex.stackexchange.com/q/270218) is reported the case of a warning terminating in the middle of a line:
```
pdfTeX warning: pdflatex (file ./p.pdf): PDF inclusion: 
Subtype in Resources dict is not a name (key 'Subtype', type <stream>); 
ignored.>] (./foo.aux)
```
This very case is not handled. However, trying to reproduce the warning I obtained:
```
pdfTeX warning: pdflatex.exe (file ./p.pdf): PDF inclusion: Subtype in Resource
s dict is not a name (key 'Subtype', type <stream>); ignored.
>] (./pdfTeX-warning-Subtype-in-Resources.aux) )
```
which is correctly parsed.

**Comment by Markvy** [comment] 2017-11-06 20:22
Better late than never :)  I'd surely have reported this to your repo, had it occurred to me that not all the official scripts live in the main one :)

**Comment by stloeffler** [comment] 2017-12-27 18:12
Thanks a lot! I (finally) pulled the changes into the Tw code base as rev. d672506)

**Closed by stloeffler** 2017-12-27 18:12 UTC
