### ISSUE TITLE
Error opening tex file

### ISSUE THREAD

**Issue by rickhev1** [TeXworks/texworks#826] opened 2017-09-04 22:04 UTC
_Steps to reproduce the problem_:

1. change the attached file type from txt to tex.
2. open the file
3. 

_Expected output_: successful open

_Actual output_: opens with error msg: 

"Layout Problem.  A problem occured (sic) while laying out the loaded document in the editor. This is caused by an issue in the underlying Qt framework and can cause TeXworks to crash under certain circumstances. The symptoms of this problem are hidden or overlapping lines. To work around this, please try one of the following: -) Turn syntax highlighting off and on -) Turn line numbers off and on -) Resize the windows We are sorry for the inconvenience"

_TeXworks version_: 0.6.2 (MiKTeX 2.9.6361). same problem with both 64-bit & 32-bit versions.
_TeXworks obtained from_: MiKTeX
_Operating system_: Windows 10, Creators Update

_Please provide any additional information below_: I tried all the things the msg. said.  I tried reinstalling MiKTex using the 32-bit version. None of that worked. If I split the file into two pieces, each opens without error.
[problem.txt](https://github.com/TeXworks/texworks/files/1275576/problem.txt)

**Comment by stloeffler** [comment] 2017-09-06 18:37
Could you please retry with the latest development build obtainable from [Bintray](https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest#files)? The file seems to work for me, but in this particular case this could be related to the computer hardware and usage.
Actually, this seems to be a duplicate of #469, which means it's a good test if b5db8e6 helped or not.

**Comment by rickhev1** [comment] 2017-09-06 19:21
​I downloaded the last file in the Bintray Files list (git_3939d19). I
opened texworks.exe from that and opened my file within that from the list
of recent files. No problem.

This raises some questions:

1. Can I uninstall Miktex and just use texworks.exe?

2. Are there both 32 & 64-bit versions of texworks​?

3. If so, how do I tell which is which from the Bintray download list?

Also, I looked at #469 but could see no relation between it and the problem
I was having.  I have never used line numbers.

Also, I don't know what you mean by b5db8e6. I will be glad to download
another version if you want me to test with that, but 3939d19 seems to work
just fine.

-Rick

**Comment by stloeffler** [comment] 2017-09-07 06:06
Thanks for testing!
1. No, you must not uninstall MiKTeX, or else you won't have the underlying (La)TeX binaries, packages, etc. You could uninstall MiKTeX's TeXworks, but even that is not necessary I think as both versions (MiKTeX and Bintray) should be able to coexist peacefully. Just update which TeXworks is used for opening tex files and you should be good.

2. No, on Bintray there is currently only a 32bit version, which does work fine on 64bit Windows however.

Regarding #469: the symptom you described (the dialog box) was implemented to try to work around #469, so I do believe that the two issues had the same underlying technical cause (line numbers etc. are just an effect of that).

b5db8e6 is the reference for the code change in which this particular bug was fixed - I included this mostly to remember it myself. 3939d19 is newer (though that is not readily obvious from the value itself) and already includes the relevant changes.

**Closed by stloeffler** 2017-09-07 06:06 UTC

**Comment by rickhev1** [comment] 2018-04-18 21:55
@AlainAtom Just wanted to mention that this issue is closed.  I have another open one like it (#831).  The problem occurs only with large files.
