### ISSUE TITLE
No tags generated for sectioning commands that span more than one line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#483] opened 2015-03-14 10:40 UTC
```
What steps will reproduce the problem?
The following sectioning command is perfectly valid LaTeX/ConTeXt code:
\section{Section Title Here
         }

The expected result would be for the section title to appear as a bookmark in 
the tags-dock. It doesn't, though. 

Instead the section title will only appear after the closing bracket (any 
closing bracket, really; see issue 328) is put on the same line as the 
beginning of the sectioning command.


What version of the product are you using? On what operating system?
I am using TeXworks Version 0.5 r.765 on Ubuntu Lucid

Please provide any additional information below.

```

Original issue reported on code.google.com by `werbungf...@googlemail.com` on 26 Mar 2011 at 9:15

**Comment by stloeffler** [comment] 2016-03-17 01:13
Duplicate of #328

**Closed by stloeffler** 2016-03-17 01:13 UTC
Labels: auto-migrated, bug
