### ISSUE TITLE
'Open recent files' doesn't change 'open' working folder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#544] opened 2015-03-14 11:04 UTC
```
What steps will reproduce the problem?
1. Start TeXWorks and click on 'open file' icon. A window is opened showing 
contains of last used folder (let's say Folder_A).
2. Change to another folder (Folder_B) and open a tex file (FileB).
3. Click 'open file'. Opened window shows Folder_B.
4. Open a 'recent file' (FileC) form menu of FileB window. Now we have two 
texworks windows one with FileB and another with FileC.
5. Click 'open file' on FileC menu bar.

What is the expected output? What do you see instead?

If FileC was in another folder (Folder_C) I would expect to see Folder_C, but I 
still see Folder_B.

If instead of open I click 'save as' I see Folder_C.

I would prefer both commands 'open' and 'save as' started at same folder.

What version of the product are you using? On what operating system?

0.5 r939 on windows compiled with mingw.



```

Original issue reported on code.google.com by `nign...@gmail.com` on 6 Oct 2011 at 4:43

**Comment by stloeffler** [comment] 2021-06-12 19:30
As separate folders for opening and saving are by design (and there are use cases for both the single-folder and the separate-folder approach), I'm closing this issue.

**Closed by stloeffler** 2021-06-12 19:30 UTC
Labels: auto-migrated, bug
