### ISSUE TITLE
TeXworks crashes when cursor reached end of file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#538] opened 2015-03-14 11:04 UTC
```
When last line of file is displayed, texworks crashes.

Reproducible consistently within a power cycle, but not between power cycles of 
the machine. Suspect some sort of DLL loading error.

Windows 7 Starter, MikTex 2.9, Texworks 0.4

Windows error message is:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	miktex-texworks.exe
  Application Version:	2.9.4201.0
  Application Timestamp:	4e335efb
  Fault Module Name:	QtGui4.dll
  Fault Module Version:	4.7.2.0
  Fault Module Timestamp:	4d8b7c2f
  Exception Code:	c0000005
  Exception Offset:	001e4557
  OS Version:	6.1.7601.2.1.0.768.11
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e78

```

Original issue reported on code.google.com by `a.shi...@gmail.com` on 21 Sep 2011 at 11:52

**Comment by stloeffler** [comment] 2016-03-17 11:49
Duplicate of #469

**Closed by stloeffler** 2016-03-17 11:49 UTC
Labels: auto-migrated, bug
