### ISSUE TITLE
No brace matching with real apostrophe (’) inside braces

### ISSUE THREAD

**Issue by ghost** [TeXworks/texworks#830] opened 2017-11-29 08:21 UTC
_Steps to reproduce the problem_:
Paste this line in TexWorks:
`Apostrophe {’} and straight quote {'}`

_Expected output_:
I’d expect the closing brace to be highlighted when the cursor is on the opening one, and vice versa.

_Actual output_:
It only works in the second example, where a straight quote is used instead of a real apostrophe.

_TeXworks version_: TeXworks 0.6.2 (AUR) [r.7ecce17d, 4/29/17 6:23 PM]
_TeXworks obtained from_: https://aur.archlinux.org/packages/texworks
_Operating system_: Archlinux

_Additional information_:
I first asked about this behaviour on tex.stackexchange.com:
https://tex.stackexchange.com/questions/390477/in-texworks-why-does-using-a-real-apostrophe-break-brace-matching

**Comment by stloeffler** [comment] 2017-12-28 20:43
This is (somewhat) by design. The same happens, e.g., with the line
`Parenthesis {(}`
but not with, e.g.,
`Parenthesis {()}`

The reason is that any unmatched delimiter breaks the highlighting. The rationale behind this is that this should only be caused with incomplete code, in which case there is no way for the program to know what the missing code is - for all it knows that could contain more delimiters.
What TeXworks considers as delimiter can be customized by editing the file ~/.TeXworks/configuration/delimiter-pairs.txt (which may be read-only by default). Your apostrophe is listed as closing delimiter, which causes your issue. Simply remove or comment the corresponding line and brace matching should work again for you as expected.

**Closed by stloeffler** 2017-12-28 20:43 UTC
