### ISSUE TITLE
Bad rendering of preview with TeXworks: yet no solution

### ISSUE THREAD

**Issue by SSebastiano** [TeXworks/texworks#1056] opened 2024-08-07 12:14 UTC
#1037 The problem of the output of TeXworks yet is still existent, without any solution (MiKTeX on windows 10 and TexWorks version 0.6.9) [issue1037](https://github.com/TeXworks/texworks/issues/1037 ). In this link there is a partial solution of the user Thomas Bäckdahl (@tbackdahl).
I wait for a solution of the problem.
Regards.

**Comment by stloeffler** [comment] 2024-12-26 11:06
Closing as duplicate of #1037

**Closed by stloeffler** 2024-12-26 11:06 UTC
Labels: bug, duplicate
